<?php focuson_ninzio_global_variables(); ?>
<?php if($GLOBALS['focuson_ninzio']['social-rss']): ?><a class="icon-rss" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-rss']); ?>" title="rss" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-facebook']): ?><a class="icon-facebook" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-facebook']); ?>" title="facebook" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-twitter']): ?><a class="icon-twitter" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-twitter']); ?>" title="twitter" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-googleplus']): ?><a class="icon-googleplus" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-googleplus']); ?>" title="google" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-youtube']): ?><a class="icon-youtube" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-youtube']); ?>" title="youtube" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-vimeo']): ?><a class="icon-vimeo" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-vimeo']); ?>" title="vimeo" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-linkedin']): ?><a class="icon-linkedin" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-linkedin']); ?>" title="linkedin" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-pinterest']): ?><a class="icon-pinterest" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-pinterest']); ?>" title="pinterest" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-flickr']): ?><a class="icon-flickr" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-flickr']); ?>" title="flickr" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-instagram']): ?><a class="icon-instagram" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-instagram']); ?>" title="instagram" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-apple']): ?><a class="icon-apple" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-apple']); ?>" title="apple" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-dribbble']): ?><a class="icon-dribbble" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-dribbble']); ?>" title="dribbble" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-android']): ?><a class="icon-android" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-android']); ?>" title="android" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-behance']): ?><a class="icon-behance" href="<?php echo esc_url($GLOBALS['focuson_ninzio']['social-behance']); ?>" title="behance" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['focuson_ninzio']['social-email']): ?><a class="icon-envelope" href="mailto:<?php echo esc_attr($GLOBALS['focuson_ninzio']['social-email']); ?>" title="email" target="_blank" ></a><?php endif; ?>